// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWj4N_REpDWQpfUYv2b11F7fAI0OhgO0I',
    appId: '1:895892457976:web:519dc7337dda2295c32e0d',
    messagingSenderId: '895892457976',
    projectId: 'aquaview-2s882',
    authDomain: 'aquaview-2s882.firebaseapp.com',
    storageBucket: 'aquaview-2s882.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3qkAmZSghrK2cSap8LKSogsOBP33_pxA',
    appId: '1:895892457976:android:d216a9c0413ff318c32e0d',
    messagingSenderId: '895892457976',
    projectId: 'aquaview-2s882',
    storageBucket: 'aquaview-2s882.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCZzhDPyjDhEyqmiT9eNDic_VH3oJMDFY',
    appId: '1:895892457976:ios:f1d34080bb360e01c32e0d',
    messagingSenderId: '895892457976',
    projectId: 'aquaview-2s882',
    storageBucket: 'aquaview-2s882.firebasestorage.app',
    iosBundleId: 'com.example.mychat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCZzhDPyjDhEyqmiT9eNDic_VH3oJMDFY',
    appId: '1:895892457976:ios:f1d34080bb360e01c32e0d',
    messagingSenderId: '895892457976',
    projectId: 'aquaview-2s882',
    storageBucket: 'aquaview-2s882.firebasestorage.app',
    iosBundleId: 'com.example.mychat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBghVC7dLTs_jZTJ8PHQ9WOIhC0524Uo3k',
    appId: '1:895892457976:web:66a3bc0f21d53f00c32e0d',
    messagingSenderId: '895892457976',
    projectId: 'aquaview-2s882',
    authDomain: 'aquaview-2s882.firebaseapp.com',
    storageBucket: 'aquaview-2s882.firebasestorage.app',
  );
}
