import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter_chat_app/auth/auth_gate.dart';
// <-- Use your app name
import 'firebase_options.dart'; // This is auto-generated by FlutterFire
import 'package:flutter_chat_app/theme/colors.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Chat App',
      theme: ThemeData(
        scaffoldBackgroundColor: AppColors.primary,
        // You can define a full theme here
      ),
      home: const AuthGate(),
    );
  }
}
